version: 2
updates:

  - package-ecosystem: "npm"
    directory: "/.githug/yaml-validator"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/website"
    schedule:
      interval: "daily"

  - package-ecosystem: "pip"
    directory: "/scripts"
    schedule:
      interval: "daily"
