openapi: 3.0.0
info:
  title: prairiewatch.dog Public API
  version: 0.1.0
servers:
  - url: https://api.prairiewatch.dog/v1
paths:
  /v0:
    /offenders:
      /twitter:
        get:
          summary: Returns a list of twitter handles associated with offenders.
          responses:
            '200':
              description: An array of twitter handle strings.
              content:
                application/json:
                  schema:
                    type: array
                    items:
                      type: string
      /websites:
        get:
          summary: Returns a list of website urls associated with offenders.
          responses:
            '200':
              description: An array of website base url strings.
              content:
                application/json:
                  schema:
                    type: array
                    items:
                      type: string
    /offender/{uuid}:
      get:
        summary: Get details for a specific offender.
        operationId: getOffender
        parameters:
          - name: uuid
            in: path
            description: An associated offender UUID.
            required: true
            schema:
              type: string
              format: uuid
        responses:
          '200':
            description: Details for a specific offender.
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/Offender'

components:
  schemas:
    Offender:
      type: object
      required:
        - name
        - uuid
      properties:
        name:
          type: string
        id:
          type: string
          format: byte
        counts:
          type: array
          items:
            $ref: '#/components/schemas/Offense'
        social_media:
          $ref: '#/components/schemas/SocialMedia'

    Offense:
      type: object
      required:
        - name
        - type
        - source
        - body
      properties:
        category:
          type: string
        subtype:
          type: string
        source:
          $ref: '#/components/schemas/Source'
        body:
          type: string

    Source:
      type: object
      required:
        - idk
      properties:
        url:
          type: string
        incident_timestamp:
          type: integer
          format: int32
        reported_timestamp:
          type: integer
          format: int32
        type:
          type: string

    SocialMedia:
      type: object
      properties:
        twitter:
          type: object
          required:
            - user_id
            - handle
          properties:
            user_id:
              type: integer
            handle:
              type: string
        websites:
          type: array
          items:
            type: string
