openapi: 3.0.0
info:
  title: prairiewatch.dog Public API
  version: 0.2.0
servers:
  - url: https://api.prairiewatch.dog/v0
paths:
  /v0:
    /offenders:
      get:
        summary: Retrieves a list of offenders based on passed-in identifiers.
        operationId: checkOffenders
          parameters:
            - name: twitter
              in: path
              description: A comma-deliniated list of twitter handles.
              required: false
              schema:
                type: string
            - name: url
              in: path
              description: A URL-encoded URL.
              required: false
              schema:
                type: string
        responses:
          '200':
            description: An array of offender details.
            content:
              application/json:
                type: object
                properties:
                  offenders:
                    type: array
                    items:
                    $ref: '#/components/schemas/Offender'
      /{uuid}:
        get:
          summary: Retrieves an offender by UUID.
          operationId: getOffender
          parameters:
            - name: uuid
              in: path
              description: The UUID of the offender.
              required: true
              schema:
                type: string
                format: uuid
          responses:
            '200':
              description: Offender details.
              content:
                application/json:
                  schema:
                    $ref: '#/components/schemas/Offender'

components:
  schemas:
    Offender:
      type: object
      required:
        - name
        - uuid
      properties:
        name:
          type: string
        id:
          type: string
          format: byte
        counts:
          type: array
          items:
            $ref: '#/components/schemas/Count'
        social_media:
          $ref: '#/components/schemas/SocialMedia'

    Count:
      type: object
      required:
        - name
        - type
        - source
        - body
      properties:
        type:
          type: string
        subtype:
          type: string
        source:
          $ref: '#/components/schemas/Source'
        body:
          type: string

    Source:
      type: object
      required:
        - idk
      properties:
        url:
          type: string
        archive_url:
          type: string
        incident_time:
          type: string
        reported_time:
          type: string
        type:
          type: string

    SocialMedia:
      type: object
      properties:
        twitter:
          type: array
          items:
            type: object
            required:
              - user_id
              - handle
            properties:
              user_id:
                type: integer
              handle:
                type: string
        websites:
          type: array
          items:
            type: string
