name: Database Test Actions

on:
  push:
    paths:
    - 'database/offenders**'

jobs:
  yaml_validator:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: npm install
      working-directory: ./.github/yaml-validator
    - name: Test yml for 'offenders'
      run: npm test offenders
      working-directory: ./.github/yaml-validator
